version: '3.8'

services:
  web:
    build: .
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quan_ly_sinh_vien
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  # Đây là "người gác cổng" sẽ làm HTTPS cho bạn
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'    # HTTP
      - '443:443'  # HTTPS
      - '81:81'    # Giao diện quản lý
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db_data: